= CISE Adaptor for AIS data
Gian_Carlo Pace <giancarlo.pace@ec.europa.eu>
v1.1, 2019-01-11

https://www.meterian.com/projects/?id=91cb8dd6-d11a-4809-a7f4-cc1ee68ba3b2[image:https://www.meterian.com/badge/pb/91cb8dd6-d11a-4809-a7f4-cc1ee68ba3b2/security[security status]]	
https://www.meterian.com/projects/?id=91cb8dd6-d11a-4809-a7f4-cc1ee68ba3b2[image:https://www.meterian.com/badge/pb/91cb8dd6-d11a-4809-a7f4-cc1ee68ba3b2/stability[stability status]]	
https://www.meterian.com/projects/?id=91cb8dd6-d11a-4809-a7f4-cc1ee68ba3b2[image:https://www.meterian.com/badge/pb/91cb8dd6-d11a-4809-a7f4-cc1ee68ba3b2/licensing[licensing status]]

:page-layout: docs
:imagesdir: assets/images
:homepage: https://github.com/ec-jrc/cise-ais-adaptor
:numbered:
:source-highlighter: Coderay coderay
ifndef::env-site[]
:toc: right
:idprefix:
:idseparator: -
//:icons: font
endif::[]
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:source-language: bash

== Overview
The CISE Adaptor for AIS data is an application to read AIS tracks encoded with NMEA messages, translate them into a stream of CISE Data Model compliant objects and to dispatch CISE Push messages to a connected CISE Gateway.

The INPUT is an AIS NMEA transcription and the OUTPUT is a corresponding number of HTTP request each of them containing a CISE PUSH message.

The AIS NMEA message type supported are two:

* Message No.1/2/3: Voyage Message Type
* Message No.5: Positional Message Type

The application allows to configure the number of vessels to collect and send in each Push message and a timeout after which the Push message will be sent whatever number of Vessel (>0) will be collected.

== Requirements
The application should preferably installed on a linux machine. Theoretically should work also in any Operative System supporting Java and having a bash shell support but it has only been tested in a GNU/Linux server.

The server should be installed with:

- JDK 11+
- Maven 3.5+

NOTE: We have been reported an issue compiling the software with the JDK 11 from IBM since it is missing a security provider.

The following JDK have been proved to build the cise-ais-adaptor properly:

- GraalVM https://www.graalvm.org/docs/getting-started/
- Amazon Corretto https://aws.amazon.com/it/corretto/
- AdoptOpenJDK https://adoptopenjdk.net/
- Zulu OpenJDK https://www.azul.com/downloads/zulu-community/?package=jdk
- Liberica JDK https://bell-sw.com/

== Compilation
Clone the git repository:
[source,bash]
----
...$ git clone git@github.com:ec-jrc/cise-ais-adaptor.git
----

After cloning the git repository is possible to compile the project using maven.
[source,bash]
----
...$ cd cise-ais-adaptor
...$ mvn clean install -U
----

== Preparing the software
After the compilation is finished, it will be created a distribution package that can be used to run the software.

[source,bash]
----
...$ cd target
...$ mv cise-ais-adaptor-bin.tar.gz /my/installation/path
...$ cd /my/installation/path
...$ tar xvfz cise-ais-adaptor.tar.gz
...$ cd cise-ais-adaptor-bin
----

== Running the AIS Adaptor
The ais-adaptor application can be started by using a script `adaptor` in the distribution root path. Using the command:

The command:
[source,bash]
----
...$ ./adaptor run
----

it will be possible to start ais-adaptor in foreground. While to run it in background is possible to launch it with:

[source,bash]
----
...$ ./adaptor start
----

.Next steps
NOTE: Please refer to the link:ais-docs/src/main/asciidoc/configuration.adoc[configuration chapter] to configure the adaptor with the parameters specific to the public administration where the ais-adaptor will be installed.

